Dependencies:
 - 'on': ['Linux']
   'require':
    'frameworks/extra-cmake-modules': '@same'

Options:
 test-before-installing: True
 require-passing-tests-on: ['Linux']
 cmake-options: -DBUILD_EXAMPLES=ON
 enable-lsan: True
