/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -p nm-active-connectioninterface /home/ilia/libQtNetworkManager/solid/networkmanager-0.7/dbus/introspection/nm-active-connection.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "nm-active-connectioninterface.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerConnectionActiveInterface
 */

OrgFreedesktopNetworkManagerConnectionActiveInterface::OrgFreedesktopNetworkManagerConnectionActiveInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerConnectionActiveInterface::~OrgFreedesktopNetworkManagerConnectionActiveInterface()
{
}


#include "nm-active-connectioninterface.moc"
