/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -p nm-device-olpc-meshinterface /home/ilia/libQtNetworkManager/libQtNetworkManager/dbus/introspection/nm-device-olpc-mesh.xml
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "nm-device-olpc-meshinterface.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerDeviceOlpcMeshInterface
 */

OrgFreedesktopNetworkManagerDeviceOlpcMeshInterface::OrgFreedesktopNetworkManagerDeviceOlpcMeshInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerDeviceOlpcMeshInterface::~OrgFreedesktopNetworkManagerDeviceOlpcMeshInterface()
{
}


#include "nm-device-olpc-meshinterface.moc"
