/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -i generic-types.h -p nm-device-greinterface /home/jgrulich/development/projects/libnm-qt/dbus/introspection/nm-device-gre.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "nm-device-greinterface.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerDeviceGreInterface
 */

OrgFreedesktopNetworkManagerDeviceGreInterface::OrgFreedesktopNetworkManagerDeviceGreInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerDeviceGreInterface::~OrgFreedesktopNetworkManagerDeviceGreInterface()
{
}


#include "nm-device-greinterface.moc"
