/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -i generic-types.h -p nm-device-wifiinterface /home/jgrulich/projects/libnm-qt/dbus/introspection/nm-device-wifi.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "nm-device-wifiinterface.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerDeviceWirelessInterface
 */

OrgFreedesktopNetworkManagerDeviceWirelessInterface::OrgFreedesktopNetworkManagerDeviceWirelessInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerDeviceWirelessInterface::~OrgFreedesktopNetworkManagerDeviceWirelessInterface()
{
}


#include "nm-device-wifiinterface.moc"
