/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -i generic-types.h -p nm-device-team introspection/nm-device-team.xml
 *
 * qdbusxml2cpp is Copyright (C) 2013 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "nm-device-team.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerDeviceTeamInterface
 */

OrgFreedesktopNetworkManagerDeviceTeamInterface::OrgFreedesktopNetworkManagerDeviceTeamInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerDeviceTeamInterface::~OrgFreedesktopNetworkManagerDeviceTeamInterface()
{
}


#include "nm-device-team.moc"
