/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -m -i generic-types.h -p nm-vpn-plugininterface /home/grulja/projects/libnm-qt/dbus/introspection/nm-vpn-plugin.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "nm-vpn-plugininterface.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerVPNPluginInterface
 */

OrgFreedesktopNetworkManagerVPNPluginInterface::OrgFreedesktopNetworkManagerVPNPluginInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerVPNPluginInterface::~OrgFreedesktopNetworkManagerVPNPluginInterface()
{
}


#include "nm-vpn-plugininterface.moc"
