/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Source file was org.freedesktop.NetworkManager.Device.WifiP2P.xml
 *
 * qdbusxml2cpp is Copyright (C) The Qt Company Ltd. and other contributors.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "wifip2pdeviceinterface.h"

/*
 * Implementation of interface class OrgFreedesktopNetworkManagerDeviceWifiP2PInterface
 */

OrgFreedesktopNetworkManagerDeviceWifiP2PInterface::OrgFreedesktopNetworkManagerDeviceWifiP2PInterface(const QString &service,
                                                                                                       const QString &path,
                                                                                                       const QDBusConnection &connection,
                                                                                                       QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

OrgFreedesktopNetworkManagerDeviceWifiP2PInterface::~OrgFreedesktopNetworkManagerDeviceWifiP2PInterface()
{
}

#include "moc_wifip2pdeviceinterface.cpp"
